Accelerate
coqui-ai/Trainer pull request #114
Opened 2023-07-12 10:39 UTC by erogol

2023-07-12 12:07 UTC, Edresson requested changes

2023-07-12 13:03 UTC, erogol commented on trainer/trainer.py
> +        return self.num_gpus > 1 and self.args.use_accelerate
it can be used for single GPU too. To be able to use some of its perks like deepspeed, TPU training, etc

2023-07-12 15:43 UTC, WeberJulian reviewed
I'm running a hifigan training with `TrainerArgs(use_accelerate=True)` to check if it works fine.

2023-07-12 16:37 UTC, erogol commented on trainer/trainer.py
> +        return self.num_gpus > 1 and self.args.use_accelerate
yeah just encounter it while training. Dropping num_gpu check.

2023-07-12 16:38 UTC, erogol commented on trainer/trainer.py
> +        return self.num_gpus > 1 and not self.args.use_accelerate and self._is_apex_available()
it shouldnt 👍

2023-07-17 12:08 UTC, Edresson approved these changes
Looks all good to me :)

2023-07-18 09:18 UTC, erogol commented on requirements.dev.txt
> +accelerate  # for testing
I don't want to mandate accelerate and it is weird that it is only in dev so I know I'll be confused. It is for my future self :)

2023-07-18 11:06 UTC, merged